name: QOL
version: '0.2'
main: net.okuri.qol.QOL
api-version: '1.20'
commands:
  getenv:
    aliases: [ env ]
    description: You can get environment variables.
    permission: qol.command.getenv
    permission-message: Permission denied
    usage: /<command> <key>
  matsign:
    aliases: [ mat ]
    description: You can edit maturation sign date.
    permission: qol.command.maturation
    permission-message: Permission denied
    usage: /<command> <x> <y> <z> <date>
  givesuperitem:
    aliases: [ gsi ]
    description: You can get super item.
    permission: qol.command.givesuperitem
    permission-message: Permission denied
    usage: /<command> <superItemType>
  superwheat:
    aliases: [ sw ]
    description: You can get super wheat.
    permission: qol.command.superwheat
    permission-message: Permission denied
    usage: /<command> <typeInt> <temperature>
  alc:
    aliases: [ alcohol ]
    description: You can get alcohol percentage.
    permission: qol.command.alc
    permission-message: Permission denied
    usage: /<command>
  producer:
    aliases: [ pro ]
    description: You can get producer.
    permission: qol.command.producer
    permission-message: Permission denied
    usage: /<command>